FROM python:3.11-slim

WORKDIR /app

# Copier les requirements
COPY requirements_winux.txt .

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements_winux.txt

# Copier l'API
COPY api_winux.py .

# Exposer le port
EXPOSE 5000

# Commande pour démarrer l'API
CMD ["python3", "api_winux.py"]

